### ISSUE TITLE
Libraries Overhaul, Epic 0: Update libraries tab on Studio Home to match course tab

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/frontend-app-library-authoring#440]
Parent ticket to track stories for this epic

- [ ] https://github.com/openedx/frontend-app-course-authoring/issues/1035
- [ ] https://github.com/openedx/frontend-app-course-authoring/issues/1081
- [ ] https://github.com/openedx/frontend-app-course-authoring/issues/1033
- [ ] https://github.com/openedx/frontend-app-course-authoring/issues/1034
- [ ] https://github.com/openedx/frontend-app-course-authoring/issues/1077
- [ ] https://github.com/openedx/frontend-app-library-authoring/issues/439
