### ISSUE TITLE
[frontend-app-library-authoring] Spring cleaning

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-library-authoring#71]
frontend-app-library-authoring hasn't seen some love in a while.  It needs:

- [x] openedx/frontend-app-library-authoring#70
- [x] openedx/frontend-app-library-authoring#72
- [ ] #81
- [ ] Rewrite class-based components as functions
- [ ] Raise test coverage to a decent level, and in the process standardize on testing strategy.

**Comment by navinkarkera** [comment]
@arbrandes Is this issue still relevant?

**Comment by arbrandes** [comment]
Pretty much.  The codebase could still benefit from some clean-ups.

**Comment by kdmccormick** [comment]
Closing per https://github.com/openedx/frontend-app-library-authoring/issues/439
